version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/jboyreau/data/wordpress_files:/var/www/html
      - php_socket:/run/php
    depends_on:
      - wordpress
    restart: always
    container_name: nginx

  wordpress:
    build: ./requirements/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - /home/jboyreau/data/wordpress_files:/var/www/html
      - php_socket:/run/php
    depends_on:
      - mariadb
    restart: on-failure
    container_name: wordpress
    env_file: .env

  mariadb:
    build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/jboyreau/data/db_data:/var/lib/mysql
    restart: unless-stopped
    container_name: mariadb
    env_file: .env

volumes:
  wordpress_files:
    driver: local
  db_data:
    driver: local
  php_socket:
    driver: local

networks:
  default:
    name: net

